source "http://rubygems.org"
gem "nokogiri"
gem "rack", "~> 1.2"
gem "active_support", ">= 3.0"
gem "haml", ">= 3.1"
gem "sinatra", ">= 1.2.6"
gem "sinatra-reloader", ">= 0.5.0"
gem "therubyracer"
gem "coffee-script"
gem "execjs"
gem "json", ">= 1.4"

